export const ABOUT_MAX_LENGTH = 165

export const BUTTON_LABEL_MAX_LENGTH = 20

export const BUTTON_LABEL_DEFAULTS = {
  call: 'Call',
  email: 'Email',
  whatsapp: 'WhatsApp',
  website: 'Website',
  saveContact: 'Save Contact',
  subscribe: 'Subscribe',
  googleMaps: 'Get Directions',
}

export const PRESET_DEFAULTS = {
  personal: {
    showLogo: false,
    showProfilePhoto: true,
    showPersonName: true,
    showDesignation: true,
    showCompanyName: false,
    showTagline: true,
    showLocation: true,
    showAbout: true,
    showContactButtons: true,
    showCallButton: true,
    showEmailButton: true,
    showWhatsappButton: true,
    showSaveContactButton: true,
    showSocialLinks: true,
    showWebsite: true,
    showSubscribe: false,
    showGoogleMaps: false,
  },
  professional: {
    showLogo: true,
    showProfilePhoto: true,
    showPersonName: true,
    showDesignation: true,
    showCompanyName: true,
    showTagline: true,
    showLocation: true,
    showAbout: true,
    showContactButtons: true,
    showCallButton: true,
    showEmailButton: true,
    showWhatsappButton: true,
    showSaveContactButton: true,
    showSocialLinks: true,
    showWebsite: true,
    showSubscribe: false,
    showGoogleMaps: false,
  },
  business: {
    showLogo: true,
    showProfilePhoto: false,
    showPersonName: false,
    showDesignation: false,
    showCompanyName: true,
    showTagline: true,
    showLocation: true,
    showAbout: true,
    showContactButtons: true,
    showCallButton: true,
    showEmailButton: true,
    showWhatsappButton: true,
    showSaveContactButton: true,
    showSocialLinks: true,
    showWebsite: true,
    showSubscribe: false,
    showGoogleMaps: false,
  },
}

export function getVisibilityFlags(cardType) {
  return PRESET_DEFAULTS[cardType] || PRESET_DEFAULTS.professional
}

export const defaultProfile = {
  cardType: 'professional',
  ...PRESET_DEFAULTS.professional,
  personName: 'Brillbrains',
  designation: '',
  companyName: 'Brillbrains',
  brandName: 'Brillbrains',
  handle: 'brillbrains',
  tagline: 'Strategic and Creative Forever',
  about:
    'Discover our latest work, useful links and the best ways to connect with our team.',
  email: 'vihaan.brillbrains@gmail.com',
  phone: '+91 8104258910',
  website: 'brillbrainsconsultants.com',
  whatsapp: '+918104258910',
  location: 'India',
  googleMapsUrl: '',
  saveContactRequireForm: true,
  buttonLabels: {
    call: 'Call',
    email: 'Email',
    whatsapp: 'WhatsApp',
    website: 'Website',
    saveContact: 'Save Contact',
    subscribe: 'Subscribe',
    googleMaps: 'Get Directions',
  },
  fontFamily: 'Inter, system-ui, sans-serif',
  typography: {
    personName: 'Inter, system-ui, sans-serif',
    designation: 'Inter, system-ui, sans-serif',
    companyName: 'Inter, system-ui, sans-serif',
    tagline: 'Inter, system-ui, sans-serif',
    location: 'Inter, system-ui, sans-serif',
    about: 'Inter, system-ui, sans-serif',
    buttonLabels: 'Inter, system-ui, sans-serif',
    footerText: 'Inter, system-ui, sans-serif',
    website: 'Inter, system-ui, sans-serif',
    googleMaps: 'Inter, system-ui, sans-serif',
  },
  logo: '/brillbrains-logo.jpg',
  logoSource: '/brillbrains-logo.jpg',
  logoSettings: {
    width: 100,
    offsetX: 0,
    offsetY: 0,
    removal: 0,
    bandHeight: 165,
  },
  coverImage: '/sample-cover.svg',
  coverSettings: {
    height: 325,
    zoom: 100,
    positionX: 50,
    positionY: 35,
    fade: 62,
    shade: 24,
    offsetY: -6,
  },
  logoBg: '#122136',
  palette: {
    primary: '#5274a3',
    accent: '#606977',
    surface: '#122136',
    ink: '#ffffff',
  },
  theme: {
    pageBackground: '#122136',
    cardBackground: '#122136',
    headingText: '#ffffff',
    designationText: '#ffffff',
    companyNameText: '#ffffff',
    taglineText: '#ffffff',
    locationText: '#ffffff',
    aboutText: '#ffffff',
    bodyText: '#ffffff',
    primaryButton: '#5274a3',
    secondaryButton: '#606977',
    saveContactButton: '#606977',
    callButton: '#5274a3',
    whatsappButton: '#5274a3',
    emailButton: '#5274a3',
    websiteButton: '#5274a3',
    linkedinButton: '#5274a3',
    instagramButton: '#5274a3',
    facebookButton: '#5274a3',
    twitterButton: '#5274a3',
    youtubeButton: '#5274a3',
    telegramButton: '#5274a3',
    footerText: '#ffffff',
    borderColor: '#2a3d4f',
    accentColor: '#606977',
  },
  branding: {
    poweredBy: true,
    label: 'Powered by Brillbrains Consultants',
    url: 'https://brillbrainsconsultants.com',
  },
  socials: [
    { platform: 'instagram', url: 'https://www.instagram.com/brillbrainsbranddevelopment' },
    { platform: 'linkedin', url: 'https://www.linkedin.com/company/brillbrains-consultants/posts/?feedView=all' },
    { platform: 'facebook', url: 'https://www.facebook.com/profile.php?id=61568944060109' },
  ],
}
